[package]
name = "expand"
version = "0.1.0"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"

[dependencies.syn]
version = "1.0.46"
default-features = false
features = ["proc-macro", "parsing"]
